/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.kintsugi.taxplatform.models.components.TransactionRead;
import com.kintsugi.taxplatform.utils.AsyncResponse;
import com.kintsugi.taxplatform.utils.Blob;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class CreateTransactionV1TransactionsPostResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Successfully created transaction
     */
    private Optional<? extends TransactionRead> transactionRead;

    @JsonCreator
    public CreateTransactionV1TransactionsPostResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends TransactionRead> transactionRead) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(transactionRead, "transactionRead");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.transactionRead = transactionRead;
    }
    
    public CreateTransactionV1TransactionsPostResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Successfully created transaction
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TransactionRead> transactionRead() {
        return (Optional<TransactionRead>) transactionRead;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public CreateTransactionV1TransactionsPostResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateTransactionV1TransactionsPostResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateTransactionV1TransactionsPostResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successfully created transaction
     */
    public CreateTransactionV1TransactionsPostResponse withTransactionRead(TransactionRead transactionRead) {
        Utils.checkNotNull(transactionRead, "transactionRead");
        this.transactionRead = Optional.ofNullable(transactionRead);
        return this;
    }


    /**
     * Successfully created transaction
     */
    public CreateTransactionV1TransactionsPostResponse withTransactionRead(Optional<? extends TransactionRead> transactionRead) {
        Utils.checkNotNull(transactionRead, "transactionRead");
        this.transactionRead = transactionRead;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateTransactionV1TransactionsPostResponse other = (CreateTransactionV1TransactionsPostResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.transactionRead, other.transactionRead);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            transactionRead);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateTransactionV1TransactionsPostResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "transactionRead", transactionRead);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends TransactionRead> transactionRead = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Successfully created transaction
         */
        public Builder transactionRead(TransactionRead transactionRead) {
            Utils.checkNotNull(transactionRead, "transactionRead");
            this.transactionRead = Optional.ofNullable(transactionRead);
            return this;
        }

        /**
         * Successfully created transaction
         */
        public Builder transactionRead(Optional<? extends TransactionRead> transactionRead) {
            Utils.checkNotNull(transactionRead, "transactionRead");
            this.transactionRead = transactionRead;
            return this;
        }

        public CreateTransactionV1TransactionsPostResponse build() {

            return new CreateTransactionV1TransactionsPostResponse(
                contentType, statusCode, rawResponse,
                transactionRead);
        }

    }
}
