/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import static com.kintsugi.taxplatform.operations.Operations.AsyncRequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.operations.GetNexusDetailsForIdV1NexusNexusIdGetRequest;
import com.kintsugi.taxplatform.operations.GetNexusDetailsForIdV1NexusNexusIdGet;
import com.kintsugi.taxplatform.utils.Headers;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class GetNexusDetailsForIdV1NexusNexusIdGetRequestBuilder {

    private String nexusId;
    private Optional<String> xOrganizationId = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetNexusDetailsForIdV1NexusNexusIdGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetNexusDetailsForIdV1NexusNexusIdGetRequestBuilder nexusId(String nexusId) {
        Utils.checkNotNull(nexusId, "nexusId");
        this.nexusId = nexusId;
        return this;
    }
                
    public GetNexusDetailsForIdV1NexusNexusIdGetRequestBuilder xOrganizationId(String xOrganizationId) {
        Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        this.xOrganizationId = Optional.of(xOrganizationId);
        return this;
    }

    public GetNexusDetailsForIdV1NexusNexusIdGetRequestBuilder xOrganizationId(Optional<String> xOrganizationId) {
        Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        this.xOrganizationId = xOrganizationId;
        return this;
    }


    private GetNexusDetailsForIdV1NexusNexusIdGetRequest buildRequest() {

        GetNexusDetailsForIdV1NexusNexusIdGetRequest request = new GetNexusDetailsForIdV1NexusNexusIdGetRequest(nexusId,
            xOrganizationId);

        return request;
    }

    public CompletableFuture<GetNexusDetailsForIdV1NexusNexusIdGetResponse> call() {
        
        AsyncRequestOperation<GetNexusDetailsForIdV1NexusNexusIdGetRequest, GetNexusDetailsForIdV1NexusNexusIdGetResponse> operation
              = new GetNexusDetailsForIdV1NexusNexusIdGet.Async(sdkConfiguration, _headers);
        GetNexusDetailsForIdV1NexusNexusIdGetRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
