/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import static com.kintsugi.taxplatform.operations.Operations.AsyncRequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.operations.GetProductsV1ProductsGetRequest;
import com.kintsugi.taxplatform.operations.GetProductsV1ProductsGet;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetProductsV1ProductsGetRequestBuilder {

    private GetProductsV1ProductsGetRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetProductsV1ProductsGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetProductsV1ProductsGetRequestBuilder request(GetProductsV1ProductsGetRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<GetProductsV1ProductsGetResponse> call() throws Exception {
        
        AsyncRequestOperation<GetProductsV1ProductsGetRequest, GetProductsV1ProductsGetResponse> operation
              = new GetProductsV1ProductsGet.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
