/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import static com.kintsugi.taxplatform.operations.Operations.AsyncRequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.operations.GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest;
import com.kintsugi.taxplatform.operations.GetRegistrationByIdV1RegistrationsRegistrationIdGet;
import com.kintsugi.taxplatform.utils.Headers;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class GetRegistrationByIdV1RegistrationsRegistrationIdGetRequestBuilder {

    private String registrationId;
    private Optional<String> reveal = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetRegistrationByIdV1RegistrationsRegistrationIdGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetRegistrationByIdV1RegistrationsRegistrationIdGetRequestBuilder registrationId(String registrationId) {
        Utils.checkNotNull(registrationId, "registrationId");
        this.registrationId = registrationId;
        return this;
    }
                
    public GetRegistrationByIdV1RegistrationsRegistrationIdGetRequestBuilder reveal(String reveal) {
        Utils.checkNotNull(reveal, "reveal");
        this.reveal = Optional.of(reveal);
        return this;
    }

    public GetRegistrationByIdV1RegistrationsRegistrationIdGetRequestBuilder reveal(Optional<String> reveal) {
        Utils.checkNotNull(reveal, "reveal");
        this.reveal = reveal;
        return this;
    }


    private GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest buildRequest() {

        GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest request = new GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest(registrationId,
            reveal);

        return request;
    }

    public CompletableFuture<GetRegistrationByIdV1RegistrationsRegistrationIdGetResponse> call() {
        
        AsyncRequestOperation<GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest, GetRegistrationByIdV1RegistrationsRegistrationIdGetResponse> operation
              = new GetRegistrationByIdV1RegistrationsRegistrationIdGet.Async(sdkConfiguration, _headers);
        GetRegistrationByIdV1RegistrationsRegistrationIdGetRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
