/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import static com.kintsugi.taxplatform.operations.Operations.AsyncRequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.components.CreditNoteCreate;
import com.kintsugi.taxplatform.models.operations.POSTCreateCreditNoteByTransactionIdRequest;
import com.kintsugi.taxplatform.operations.POSTCreateCreditNoteByTransactionId;
import com.kintsugi.taxplatform.utils.Headers;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class POSTCreateCreditNoteByTransactionIdRequestBuilder {

    private String originalTransactionId;
    private CreditNoteCreate creditNoteCreate;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public POSTCreateCreditNoteByTransactionIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder originalTransactionId(String originalTransactionId) {
        Utils.checkNotNull(originalTransactionId, "originalTransactionId");
        this.originalTransactionId = originalTransactionId;
        return this;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder creditNoteCreate(CreditNoteCreate creditNoteCreate) {
        Utils.checkNotNull(creditNoteCreate, "creditNoteCreate");
        this.creditNoteCreate = creditNoteCreate;
        return this;
    }


    private POSTCreateCreditNoteByTransactionIdRequest buildRequest() {

        POSTCreateCreditNoteByTransactionIdRequest request = new POSTCreateCreditNoteByTransactionIdRequest(originalTransactionId,
            creditNoteCreate);

        return request;
    }

    public CompletableFuture<POSTCreateCreditNoteByTransactionIdResponse> call() throws Exception {
        
        AsyncRequestOperation<POSTCreateCreditNoteByTransactionIdRequest, POSTCreateCreditNoteByTransactionIdResponse> operation
              = new POSTCreateCreditNoteByTransactionId.Async(sdkConfiguration, _headers);
        POSTCreateCreditNoteByTransactionIdRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
