/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.kintsugi.taxplatform.models.components.CustomerTaxRegistrationRead;
import com.kintsugi.taxplatform.utils.AsyncResponse;
import com.kintsugi.taxplatform.utils.Blob;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Successful Response
     */
    private Optional<? extends CustomerTaxRegistrationRead> customerTaxRegistrationRead;

    @JsonCreator
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends CustomerTaxRegistrationRead> customerTaxRegistrationRead) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(customerTaxRegistrationRead, "customerTaxRegistrationRead");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.customerTaxRegistrationRead = customerTaxRegistrationRead;
    }
    
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Successful Response
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CustomerTaxRegistrationRead> customerTaxRegistrationRead() {
        return (Optional<CustomerTaxRegistrationRead>) customerTaxRegistrationRead;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successful Response
     */
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse withCustomerTaxRegistrationRead(CustomerTaxRegistrationRead customerTaxRegistrationRead) {
        Utils.checkNotNull(customerTaxRegistrationRead, "customerTaxRegistrationRead");
        this.customerTaxRegistrationRead = Optional.ofNullable(customerTaxRegistrationRead);
        return this;
    }


    /**
     * Successful Response
     */
    public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse withCustomerTaxRegistrationRead(Optional<? extends CustomerTaxRegistrationRead> customerTaxRegistrationRead) {
        Utils.checkNotNull(customerTaxRegistrationRead, "customerTaxRegistrationRead");
        this.customerTaxRegistrationRead = customerTaxRegistrationRead;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse other = (UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.customerTaxRegistrationRead, other.customerTaxRegistrationRead);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            customerTaxRegistrationRead);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "customerTaxRegistrationRead", customerTaxRegistrationRead);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends CustomerTaxRegistrationRead> customerTaxRegistrationRead = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Successful Response
         */
        public Builder customerTaxRegistrationRead(CustomerTaxRegistrationRead customerTaxRegistrationRead) {
            Utils.checkNotNull(customerTaxRegistrationRead, "customerTaxRegistrationRead");
            this.customerTaxRegistrationRead = Optional.ofNullable(customerTaxRegistrationRead);
            return this;
        }

        /**
         * Successful Response
         */
        public Builder customerTaxRegistrationRead(Optional<? extends CustomerTaxRegistrationRead> customerTaxRegistrationRead) {
            Utils.checkNotNull(customerTaxRegistrationRead, "customerTaxRegistrationRead");
            this.customerTaxRegistrationRead = customerTaxRegistrationRead;
            return this;
        }

        public UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse build() {

            return new UpsertCustomerTaxRegistrationV1CustomersCustomerIdTaxRegistrationsPostResponse(
                contentType, statusCode, rawResponse,
                customerTaxRegistrationRead);
        }

    }
}
