/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import static com.kintsugi.taxplatform.operations.Operations.RequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.components.TransactionPublicRequest;
import com.kintsugi.taxplatform.operations.CreateTransactionV1TransactionsPost;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;

public class CreateTransactionV1TransactionsPostRequestBuilder {

    private TransactionPublicRequest request;
    private final SDKConfiguration sdkConfiguration;

    public CreateTransactionV1TransactionsPostRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateTransactionV1TransactionsPostRequestBuilder request(TransactionPublicRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateTransactionV1TransactionsPostResponse call() throws Exception {
        
        RequestOperation<TransactionPublicRequest, CreateTransactionV1TransactionsPostResponse> operation
              = new CreateTransactionV1TransactionsPost.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
