/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import static com.kintsugi.taxplatform.operations.Operations.RequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.operations.GetCustomerByIdV1CustomersCustomerIdGetOperation;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class GetCustomerByIdV1CustomersCustomerIdGetRequestBuilder {

    private String customerId;
    private final SDKConfiguration sdkConfiguration;

    public GetCustomerByIdV1CustomersCustomerIdGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetCustomerByIdV1CustomersCustomerIdGetRequestBuilder customerId(String customerId) {
        Utils.checkNotNull(customerId, "customerId");
        this.customerId = customerId;
        return this;
    }


    private GetCustomerByIdV1CustomersCustomerIdGetRequest buildRequest() {

        GetCustomerByIdV1CustomersCustomerIdGetRequest request = new GetCustomerByIdV1CustomersCustomerIdGetRequest(customerId);

        return request;
    }

    public GetCustomerByIdV1CustomersCustomerIdGetResponse call() throws Exception {
        
        RequestOperation<GetCustomerByIdV1CustomersCustomerIdGetRequest, GetCustomerByIdV1CustomersCustomerIdGetResponse> operation
              = new GetCustomerByIdV1CustomersCustomerIdGetOperation(sdkConfiguration);
        GetCustomerByIdV1CustomersCustomerIdGetRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
