/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kintsugi.taxplatform.models.components.CountryCodeEnum;
import com.kintsugi.taxplatform.utils.OneOfDeserializer;
import com.kintsugi.taxplatform.utils.TypedObject;
import com.kintsugi.taxplatform.utils.Utils.JsonShape;
import com.kintsugi.taxplatform.utils.Utils.TypeReferenceWithShape;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

@JsonDeserialize(using = GetExemptionsV1ExemptionsGetCountryCode._Deserializer.class)
public class GetExemptionsV1ExemptionsGetCountryCode {

    @JsonValue
    private final TypedObject value;
    
    private GetExemptionsV1ExemptionsGetCountryCode(TypedObject value) {
        this.value = value;
    }

    public static GetExemptionsV1ExemptionsGetCountryCode of(CountryCodeEnum value) {
        Utils.checkNotNull(value, "value");
        return new GetExemptionsV1ExemptionsGetCountryCode(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetExemptionsV1ExemptionsGetCountryCode of(String value) {
        Utils.checkNotNull(value, "value");
        return new GetExemptionsV1ExemptionsGetCountryCode(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.kintsugi.taxplatform.models.components.CountryCodeEnum}</li>
     * <li>{@code java.lang.String}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetExemptionsV1ExemptionsGetCountryCode other = (GetExemptionsV1ExemptionsGetCountryCode) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<GetExemptionsV1ExemptionsGetCountryCode> {

        public _Deserializer() {
            super(GetExemptionsV1ExemptionsGetCountryCode.class, false,
                  TypeReferenceWithShape.of(new TypeReference<CountryCodeEnum>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetExemptionsV1ExemptionsGetCountryCode.class,
                "value", value);
    }

}

