/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.kintsugi.taxplatform.utils.SpeakeasyMetadata;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class GetProductByIdV1ProductsProductIdGetRequest {
    /**
     * The unique identifier for the product you want to retrieve.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=product_id")
    private String productId;

    @JsonCreator
    public GetProductByIdV1ProductsProductIdGetRequest(
            String productId) {
        Utils.checkNotNull(productId, "productId");
        this.productId = productId;
    }

    /**
     * The unique identifier for the product you want to retrieve.
     */
    @JsonIgnore
    public String productId() {
        return productId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier for the product you want to retrieve.
     */
    public GetProductByIdV1ProductsProductIdGetRequest withProductId(String productId) {
        Utils.checkNotNull(productId, "productId");
        this.productId = productId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetProductByIdV1ProductsProductIdGetRequest other = (GetProductByIdV1ProductsProductIdGetRequest) o;
        return 
            Utils.enhancedDeepEquals(this.productId, other.productId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            productId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetProductByIdV1ProductsProductIdGetRequest.class,
                "productId", productId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String productId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The unique identifier for the product you want to retrieve.
         */
        public Builder productId(String productId) {
            Utils.checkNotNull(productId, "productId");
            this.productId = productId;
            return this;
        }

        public GetProductByIdV1ProductsProductIdGetRequest build() {

            return new GetProductByIdV1ProductsProductIdGetRequest(
                productId);
        }

    }
}
