/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.kintsugi.taxplatform.utils.SpeakeasyMetadata;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class GetTransactionByIdV1TransactionsTransactionIdGetRequest {
    /**
     * The unique identifier of the transaction to retrieve.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=transaction_id")
    private String transactionId;

    @JsonCreator
    public GetTransactionByIdV1TransactionsTransactionIdGetRequest(
            String transactionId) {
        Utils.checkNotNull(transactionId, "transactionId");
        this.transactionId = transactionId;
    }

    /**
     * The unique identifier of the transaction to retrieve.
     */
    @JsonIgnore
    public String transactionId() {
        return transactionId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier of the transaction to retrieve.
     */
    public GetTransactionByIdV1TransactionsTransactionIdGetRequest withTransactionId(String transactionId) {
        Utils.checkNotNull(transactionId, "transactionId");
        this.transactionId = transactionId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionByIdV1TransactionsTransactionIdGetRequest other = (GetTransactionByIdV1TransactionsTransactionIdGetRequest) o;
        return 
            Utils.enhancedDeepEquals(this.transactionId, other.transactionId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            transactionId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransactionByIdV1TransactionsTransactionIdGetRequest.class,
                "transactionId", transactionId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String transactionId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The unique identifier of the transaction to retrieve.
         */
        public Builder transactionId(String transactionId) {
            Utils.checkNotNull(transactionId, "transactionId");
            this.transactionId = transactionId;
            return this;
        }

        public GetTransactionByIdV1TransactionsTransactionIdGetRequest build() {

            return new GetTransactionByIdV1TransactionsTransactionIdGetRequest(
                transactionId);
        }

    }
}
