/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import static com.kintsugi.taxplatform.operations.Operations.RequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.operations.GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGet;
import com.kintsugi.taxplatform.utils.Headers;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequestBuilder {

    private String customerId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequestBuilder customerId(String customerId) {
        Utils.checkNotNull(customerId, "customerId");
        this.customerId = customerId;
        return this;
    }


    private GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest buildRequest() {

        GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest request = new GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest(customerId);

        return request;
    }

    public GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetResponse call() throws Exception {
        
        RequestOperation<GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest, GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetResponse> operation
              = new GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGet.Sync(sdkConfiguration, _headers);
        GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
