/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import static com.kintsugi.taxplatform.operations.Operations.RequestOperation;

import com.kintsugi.taxplatform.SDKConfiguration;
import com.kintsugi.taxplatform.models.components.CreditNoteCreate;
import com.kintsugi.taxplatform.operations.POSTCreateCreditNoteByTransactionIdOperation;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class POSTCreateCreditNoteByTransactionIdRequestBuilder {

    private POSTCreateCreditNoteByTransactionIdSecurity security;
    private String originalTransactionId;
    private Optional<String> xOrganizationId = Optional.empty();
    private CreditNoteCreate creditNoteCreate;
    private final SDKConfiguration sdkConfiguration;

    public POSTCreateCreditNoteByTransactionIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder security(POSTCreateCreditNoteByTransactionIdSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder originalTransactionId(String originalTransactionId) {
        Utils.checkNotNull(originalTransactionId, "originalTransactionId");
        this.originalTransactionId = originalTransactionId;
        return this;
    }
                
    public POSTCreateCreditNoteByTransactionIdRequestBuilder xOrganizationId(String xOrganizationId) {
        Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        this.xOrganizationId = Optional.of(xOrganizationId);
        return this;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder xOrganizationId(Optional<String> xOrganizationId) {
        Utils.checkNotNull(xOrganizationId, "xOrganizationId");
        this.xOrganizationId = xOrganizationId;
        return this;
    }

    public POSTCreateCreditNoteByTransactionIdRequestBuilder creditNoteCreate(CreditNoteCreate creditNoteCreate) {
        Utils.checkNotNull(creditNoteCreate, "creditNoteCreate");
        this.creditNoteCreate = creditNoteCreate;
        return this;
    }


    private POSTCreateCreditNoteByTransactionIdRequest buildRequest() {

        POSTCreateCreditNoteByTransactionIdRequest request = new POSTCreateCreditNoteByTransactionIdRequest(originalTransactionId,
            xOrganizationId,
            creditNoteCreate);

        return request;
    }

    public POSTCreateCreditNoteByTransactionIdResponse call() throws Exception {
        
        RequestOperation<POSTCreateCreditNoteByTransactionIdRequest, POSTCreateCreditNoteByTransactionIdResponse> operation
              = new POSTCreateCreditNoteByTransactionIdOperation(sdkConfiguration, security);
        POSTCreateCreditNoteByTransactionIdRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
