/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.kintsugi.taxplatform.models.components.PhysicalNexusUpdate;
import com.kintsugi.taxplatform.utils.SpeakeasyMetadata;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest {
    /**
     * The unique identifier of the physical
     *                                 nexus to update.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=physical_nexus_id")
    private String physicalNexusId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private PhysicalNexusUpdate physicalNexusUpdate;

    @JsonCreator
    public UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest(
            String physicalNexusId,
            PhysicalNexusUpdate physicalNexusUpdate) {
        Utils.checkNotNull(physicalNexusId, "physicalNexusId");
        Utils.checkNotNull(physicalNexusUpdate, "physicalNexusUpdate");
        this.physicalNexusId = physicalNexusId;
        this.physicalNexusUpdate = physicalNexusUpdate;
    }

    /**
     * The unique identifier of the physical
     *                                 nexus to update.
     */
    @JsonIgnore
    public String physicalNexusId() {
        return physicalNexusId;
    }

    @JsonIgnore
    public PhysicalNexusUpdate physicalNexusUpdate() {
        return physicalNexusUpdate;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier of the physical
     *                                 nexus to update.
     */
    public UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest withPhysicalNexusId(String physicalNexusId) {
        Utils.checkNotNull(physicalNexusId, "physicalNexusId");
        this.physicalNexusId = physicalNexusId;
        return this;
    }

    public UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest withPhysicalNexusUpdate(PhysicalNexusUpdate physicalNexusUpdate) {
        Utils.checkNotNull(physicalNexusUpdate, "physicalNexusUpdate");
        this.physicalNexusUpdate = physicalNexusUpdate;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest other = (UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest) o;
        return 
            Utils.enhancedDeepEquals(this.physicalNexusId, other.physicalNexusId) &&
            Utils.enhancedDeepEquals(this.physicalNexusUpdate, other.physicalNexusUpdate);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            physicalNexusId, physicalNexusUpdate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest.class,
                "physicalNexusId", physicalNexusId,
                "physicalNexusUpdate", physicalNexusUpdate);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String physicalNexusId;

        private PhysicalNexusUpdate physicalNexusUpdate;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The unique identifier of the physical
         *                                 nexus to update.
         */
        public Builder physicalNexusId(String physicalNexusId) {
            Utils.checkNotNull(physicalNexusId, "physicalNexusId");
            this.physicalNexusId = physicalNexusId;
            return this;
        }


        public Builder physicalNexusUpdate(PhysicalNexusUpdate physicalNexusUpdate) {
            Utils.checkNotNull(physicalNexusUpdate, "physicalNexusUpdate");
            this.physicalNexusUpdate = physicalNexusUpdate;
            return this;
        }

        public UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest build() {

            return new UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIdPutRequest(
                physicalNexusId, physicalNexusUpdate);
        }

    }
}
