workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    kintsugi-overlay:
        inputs:
            - location: https://api.trykintsugi.com/openapi.json
        overlays:
            - location: ./overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay
targets:
    java:
        target: java
        source: kintsugi-overlay
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
