/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum AddressStatus {
    UNVERIFIED("UNVERIFIED"),
    INVALID("INVALID"),
    PARTIALLY_VERIFIED("PARTIALLY_VERIFIED"),
    VERIFIED("VERIFIED"),
    UNVERIFIABLE("UNVERIFIABLE"),
    BLANK("BLANK");

    @JsonValue
    private final String value;

    AddressStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AddressStatus> fromValue(String value) {
        for (AddressStatus o: AddressStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

