/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum AppliedTo {
    TRANSACTION("TRANSACTION"),
    TRANSACTION_ITEM("TRANSACTION_ITEM");

    @JsonValue
    private final String value;

    AppliedTo(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AppliedTo> fromValue(String value) {
        for (AppliedTo o: AppliedTo.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

