/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.kintsugi.taxplatform.utils.LazySingletonValue;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * ConnecticutFields
 * 
 * <p>State-specific fields for Connecticut registration import (myconneCT / DRS).
 */
public class ConnecticutFields {

    @JsonProperty("registration_type")
    private ConnecticutRegistrationType registrationType;

    /**
     * Business name as registered with the state of Connecticut.
     */
    @JsonProperty("business_name")
    private String businessName;

    /**
     * Connecticut tax registration number issued by DRS.
     */
    @JsonProperty("ct_tax_registration_number")
    private String ctTaxRegistrationNumber;

    /**
     * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
     * login credentials.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("registration_id")
    private JsonNullable<String> registrationId;

    /**
     * Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not
     * include $ or commas).
     */
    @JsonProperty("last_payment_to_state")
    private String lastPaymentToState;

    /**
     * Whether the customer has completed MFA setup in their Connecticut tax account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mfa_completed")
    private Optional<Boolean> mfaCompleted;

    @JsonCreator
    public ConnecticutFields(
            @JsonProperty("registration_type") ConnecticutRegistrationType registrationType,
            @JsonProperty("business_name") String businessName,
            @JsonProperty("ct_tax_registration_number") String ctTaxRegistrationNumber,
            @JsonProperty("registration_id") JsonNullable<String> registrationId,
            @JsonProperty("last_payment_to_state") String lastPaymentToState,
            @JsonProperty("mfa_completed") Optional<Boolean> mfaCompleted) {
        Utils.checkNotNull(registrationType, "registrationType");
        Utils.checkNotNull(businessName, "businessName");
        Utils.checkNotNull(ctTaxRegistrationNumber, "ctTaxRegistrationNumber");
        Utils.checkNotNull(registrationId, "registrationId");
        Utils.checkNotNull(lastPaymentToState, "lastPaymentToState");
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.registrationType = registrationType;
        this.businessName = businessName;
        this.ctTaxRegistrationNumber = ctTaxRegistrationNumber;
        this.registrationId = registrationId;
        this.lastPaymentToState = lastPaymentToState;
        this.mfaCompleted = mfaCompleted;
    }
    
    public ConnecticutFields(
            ConnecticutRegistrationType registrationType,
            String businessName,
            String ctTaxRegistrationNumber,
            String lastPaymentToState) {
        this(registrationType, businessName, ctTaxRegistrationNumber,
            JsonNullable.undefined(), lastPaymentToState, Optional.empty());
    }

    @JsonIgnore
    public ConnecticutRegistrationType registrationType() {
        return registrationType;
    }

    /**
     * Business name as registered with the state of Connecticut.
     */
    @JsonIgnore
    public String businessName() {
        return businessName;
    }

    /**
     * Connecticut tax registration number issued by DRS.
     */
    @JsonIgnore
    public String ctTaxRegistrationNumber() {
        return ctTaxRegistrationNumber;
    }

    /**
     * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
     * login credentials.
     */
    @JsonIgnore
    public JsonNullable<String> registrationId() {
        return registrationId;
    }

    /**
     * Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not
     * include $ or commas).
     */
    @JsonIgnore
    public String lastPaymentToState() {
        return lastPaymentToState;
    }

    /**
     * Whether the customer has completed MFA setup in their Connecticut tax account.
     */
    @JsonIgnore
    public Optional<Boolean> mfaCompleted() {
        return mfaCompleted;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ConnecticutFields withRegistrationType(ConnecticutRegistrationType registrationType) {
        Utils.checkNotNull(registrationType, "registrationType");
        this.registrationType = registrationType;
        return this;
    }

    /**
     * Business name as registered with the state of Connecticut.
     */
    public ConnecticutFields withBusinessName(String businessName) {
        Utils.checkNotNull(businessName, "businessName");
        this.businessName = businessName;
        return this;
    }

    /**
     * Connecticut tax registration number issued by DRS.
     */
    public ConnecticutFields withCtTaxRegistrationNumber(String ctTaxRegistrationNumber) {
        Utils.checkNotNull(ctTaxRegistrationNumber, "ctTaxRegistrationNumber");
        this.ctTaxRegistrationNumber = ctTaxRegistrationNumber;
        return this;
    }

    /**
     * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
     * login credentials.
     */
    public ConnecticutFields withRegistrationId(String registrationId) {
        Utils.checkNotNull(registrationId, "registrationId");
        this.registrationId = JsonNullable.of(registrationId);
        return this;
    }

    /**
     * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
     * login credentials.
     */
    public ConnecticutFields withRegistrationId(JsonNullable<String> registrationId) {
        Utils.checkNotNull(registrationId, "registrationId");
        this.registrationId = registrationId;
        return this;
    }

    /**
     * Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not
     * include $ or commas).
     */
    public ConnecticutFields withLastPaymentToState(String lastPaymentToState) {
        Utils.checkNotNull(lastPaymentToState, "lastPaymentToState");
        this.lastPaymentToState = lastPaymentToState;
        return this;
    }

    /**
     * Whether the customer has completed MFA setup in their Connecticut tax account.
     */
    public ConnecticutFields withMfaCompleted(boolean mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = Optional.ofNullable(mfaCompleted);
        return this;
    }


    /**
     * Whether the customer has completed MFA setup in their Connecticut tax account.
     */
    public ConnecticutFields withMfaCompleted(Optional<Boolean> mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = mfaCompleted;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConnecticutFields other = (ConnecticutFields) o;
        return 
            Utils.enhancedDeepEquals(this.registrationType, other.registrationType) &&
            Utils.enhancedDeepEquals(this.businessName, other.businessName) &&
            Utils.enhancedDeepEquals(this.ctTaxRegistrationNumber, other.ctTaxRegistrationNumber) &&
            Utils.enhancedDeepEquals(this.registrationId, other.registrationId) &&
            Utils.enhancedDeepEquals(this.lastPaymentToState, other.lastPaymentToState) &&
            Utils.enhancedDeepEquals(this.mfaCompleted, other.mfaCompleted);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            registrationType, businessName, ctTaxRegistrationNumber,
            registrationId, lastPaymentToState, mfaCompleted);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ConnecticutFields.class,
                "registrationType", registrationType,
                "businessName", businessName,
                "ctTaxRegistrationNumber", ctTaxRegistrationNumber,
                "registrationId", registrationId,
                "lastPaymentToState", lastPaymentToState,
                "mfaCompleted", mfaCompleted);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ConnecticutRegistrationType registrationType;

        private String businessName;

        private String ctTaxRegistrationNumber;

        private JsonNullable<String> registrationId = JsonNullable.undefined();

        private String lastPaymentToState;

        private Optional<Boolean> mfaCompleted;

        private Builder() {
          // force use of static builder() method
        }


        public Builder registrationType(ConnecticutRegistrationType registrationType) {
            Utils.checkNotNull(registrationType, "registrationType");
            this.registrationType = registrationType;
            return this;
        }


        /**
         * Business name as registered with the state of Connecticut.
         */
        public Builder businessName(String businessName) {
            Utils.checkNotNull(businessName, "businessName");
            this.businessName = businessName;
            return this;
        }


        /**
         * Connecticut tax registration number issued by DRS.
         */
        public Builder ctTaxRegistrationNumber(String ctTaxRegistrationNumber) {
            Utils.checkNotNull(ctTaxRegistrationNumber, "ctTaxRegistrationNumber");
            this.ctTaxRegistrationNumber = ctTaxRegistrationNumber;
            return this;
        }


        /**
         * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
         * login credentials.
         */
        public Builder registrationId(String registrationId) {
            Utils.checkNotNull(registrationId, "registrationId");
            this.registrationId = JsonNullable.of(registrationId);
            return this;
        }

        /**
         * Connecticut DRS registration number used on the filing (AP) report; distinct from the myconneCT
         * login credentials.
         */
        public Builder registrationId(JsonNullable<String> registrationId) {
            Utils.checkNotNull(registrationId, "registrationId");
            this.registrationId = registrationId;
            return this;
        }


        /**
         * Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not
         * include $ or commas).
         */
        public Builder lastPaymentToState(String lastPaymentToState) {
            Utils.checkNotNull(lastPaymentToState, "lastPaymentToState");
            this.lastPaymentToState = lastPaymentToState;
            return this;
        }


        /**
         * Whether the customer has completed MFA setup in their Connecticut tax account.
         */
        public Builder mfaCompleted(boolean mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = Optional.ofNullable(mfaCompleted);
            return this;
        }

        /**
         * Whether the customer has completed MFA setup in their Connecticut tax account.
         */
        public Builder mfaCompleted(Optional<Boolean> mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = mfaCompleted;
            return this;
        }

        public ConnecticutFields build() {
            if (mfaCompleted == null) {
                mfaCompleted = _SINGLETON_VALUE_MfaCompleted.value();
            }

            return new ConnecticutFields(
                registrationType, businessName, ctTaxRegistrationNumber,
                registrationId, lastPaymentToState, mfaCompleted);
        }


        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_MfaCompleted =
                new LazySingletonValue<>(
                        "mfa_completed",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});
    }
}
