/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class CustomerTaxRegistrationCreateUpdate {

    @JsonProperty("tax_id")
    private String taxId;

    @JsonCreator
    public CustomerTaxRegistrationCreateUpdate(
            @JsonProperty("tax_id") String taxId) {
        Utils.checkNotNull(taxId, "taxId");
        this.taxId = taxId;
    }

    @JsonIgnore
    public String taxId() {
        return taxId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CustomerTaxRegistrationCreateUpdate withTaxId(String taxId) {
        Utils.checkNotNull(taxId, "taxId");
        this.taxId = taxId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomerTaxRegistrationCreateUpdate other = (CustomerTaxRegistrationCreateUpdate) o;
        return 
            Utils.enhancedDeepEquals(this.taxId, other.taxId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            taxId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CustomerTaxRegistrationCreateUpdate.class,
                "taxId", taxId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String taxId;

        private Builder() {
          // force use of static builder() method
        }


        public Builder taxId(String taxId) {
            Utils.checkNotNull(taxId, "taxId");
            this.taxId = taxId;
            return this;
        }

        public CustomerTaxRegistrationCreateUpdate build() {

            return new CustomerTaxRegistrationCreateUpdate(
                taxId);
        }

    }
}
