/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.kintsugi.taxplatform.utils.LazySingletonValue;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DiscountBuilder {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_id")
    private Optional<String> externalId;


    @JsonProperty("applied_to")
    private AppliedTo appliedTo;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("discount_amount")
    private Optional<Double> discountAmount;

    @JsonCreator
    public DiscountBuilder(
            @JsonProperty("external_id") Optional<String> externalId,
            @JsonProperty("applied_to") AppliedTo appliedTo,
            @JsonProperty("discount_amount") Optional<Double> discountAmount) {
        Utils.checkNotNull(externalId, "externalId");
        Utils.checkNotNull(appliedTo, "appliedTo");
        Utils.checkNotNull(discountAmount, "discountAmount");
        this.externalId = externalId;
        this.appliedTo = appliedTo;
        this.discountAmount = discountAmount;
    }
    
    public DiscountBuilder(
            AppliedTo appliedTo) {
        this(Optional.empty(), appliedTo, Optional.empty());
    }

    @JsonIgnore
    public Optional<String> externalId() {
        return externalId;
    }

    @JsonIgnore
    public AppliedTo appliedTo() {
        return appliedTo;
    }

    @JsonIgnore
    public Optional<Double> discountAmount() {
        return discountAmount;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DiscountBuilder withExternalId(String externalId) {
        Utils.checkNotNull(externalId, "externalId");
        this.externalId = Optional.ofNullable(externalId);
        return this;
    }


    public DiscountBuilder withExternalId(Optional<String> externalId) {
        Utils.checkNotNull(externalId, "externalId");
        this.externalId = externalId;
        return this;
    }

    public DiscountBuilder withAppliedTo(AppliedTo appliedTo) {
        Utils.checkNotNull(appliedTo, "appliedTo");
        this.appliedTo = appliedTo;
        return this;
    }

    public DiscountBuilder withDiscountAmount(double discountAmount) {
        Utils.checkNotNull(discountAmount, "discountAmount");
        this.discountAmount = Optional.ofNullable(discountAmount);
        return this;
    }


    public DiscountBuilder withDiscountAmount(Optional<Double> discountAmount) {
        Utils.checkNotNull(discountAmount, "discountAmount");
        this.discountAmount = discountAmount;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DiscountBuilder other = (DiscountBuilder) o;
        return 
            Utils.enhancedDeepEquals(this.externalId, other.externalId) &&
            Utils.enhancedDeepEquals(this.appliedTo, other.appliedTo) &&
            Utils.enhancedDeepEquals(this.discountAmount, other.discountAmount);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            externalId, appliedTo, discountAmount);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DiscountBuilder.class,
                "externalId", externalId,
                "appliedTo", appliedTo,
                "discountAmount", discountAmount);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> externalId = Optional.empty();

        private AppliedTo appliedTo;

        private Optional<Double> discountAmount;

        private Builder() {
          // force use of static builder() method
        }


        public Builder externalId(String externalId) {
            Utils.checkNotNull(externalId, "externalId");
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        public Builder externalId(Optional<String> externalId) {
            Utils.checkNotNull(externalId, "externalId");
            this.externalId = externalId;
            return this;
        }


        public Builder appliedTo(AppliedTo appliedTo) {
            Utils.checkNotNull(appliedTo, "appliedTo");
            this.appliedTo = appliedTo;
            return this;
        }


        public Builder discountAmount(double discountAmount) {
            Utils.checkNotNull(discountAmount, "discountAmount");
            this.discountAmount = Optional.ofNullable(discountAmount);
            return this;
        }

        public Builder discountAmount(Optional<Double> discountAmount) {
            Utils.checkNotNull(discountAmount, "discountAmount");
            this.discountAmount = discountAmount;
            return this;
        }

        public DiscountBuilder build() {
            if (discountAmount == null) {
                discountAmount = _SINGLETON_VALUE_DiscountAmount.value();
            }

            return new DiscountBuilder(
                externalId, appliedTo, discountAmount);
        }


        private static final LazySingletonValue<Optional<Double>> _SINGLETON_VALUE_DiscountAmount =
                new LazySingletonValue<>(
                        "discount_amount",
                        "\"0.00\"",
                        new TypeReference<Optional<Double>>() {});
    }
}
