/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.kintsugi.taxplatform.utils.LazySingletonValue;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * KansasFields
 * 
 * <p>State-specific fields for Kansas Customer Service Center portal registration import.
 * 
 * <p>Values are plaintext in API request/response models. Before persistence,
 * ``access_code`` is encrypted with ``kintsugi_encrypt``
 * (see ``finalize_jurisdiction_specific_fields_for_storage``).
 */
public class KansasFields {

    @JsonProperty("registration_type")
    private KansasRegistrationType registrationType;

    /**
     * State-registered business name as shown in the Kansas tax portal.
     */
    @JsonProperty("business_name")
    private String businessName;

    /**
     * Kansas state-issued tax identification number.
     */
    @JsonProperty("ks_state_tax_id")
    private String ksStateTaxId;

    /**
     * Kansas Access Code used for portal access / third-party setup.
     */
    @JsonProperty("access_code")
    private String accessCode;

    /**
     * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
     * informed via footer copy; Kintsugi implements access on their behalf.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("third_party_access_enabled")
    private Optional<Boolean> thirdPartyAccessEnabled;

    @JsonCreator
    public KansasFields(
            @JsonProperty("registration_type") KansasRegistrationType registrationType,
            @JsonProperty("business_name") String businessName,
            @JsonProperty("ks_state_tax_id") String ksStateTaxId,
            @JsonProperty("access_code") String accessCode,
            @JsonProperty("third_party_access_enabled") Optional<Boolean> thirdPartyAccessEnabled) {
        Utils.checkNotNull(registrationType, "registrationType");
        Utils.checkNotNull(businessName, "businessName");
        Utils.checkNotNull(ksStateTaxId, "ksStateTaxId");
        Utils.checkNotNull(accessCode, "accessCode");
        Utils.checkNotNull(thirdPartyAccessEnabled, "thirdPartyAccessEnabled");
        this.registrationType = registrationType;
        this.businessName = businessName;
        this.ksStateTaxId = ksStateTaxId;
        this.accessCode = accessCode;
        this.thirdPartyAccessEnabled = thirdPartyAccessEnabled;
    }
    
    public KansasFields(
            KansasRegistrationType registrationType,
            String businessName,
            String ksStateTaxId,
            String accessCode) {
        this(registrationType, businessName, ksStateTaxId,
            accessCode, Optional.empty());
    }

    @JsonIgnore
    public KansasRegistrationType registrationType() {
        return registrationType;
    }

    /**
     * State-registered business name as shown in the Kansas tax portal.
     */
    @JsonIgnore
    public String businessName() {
        return businessName;
    }

    /**
     * Kansas state-issued tax identification number.
     */
    @JsonIgnore
    public String ksStateTaxId() {
        return ksStateTaxId;
    }

    /**
     * Kansas Access Code used for portal access / third-party setup.
     */
    @JsonIgnore
    public String accessCode() {
        return accessCode;
    }

    /**
     * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
     * informed via footer copy; Kintsugi implements access on their behalf.
     */
    @JsonIgnore
    public Optional<Boolean> thirdPartyAccessEnabled() {
        return thirdPartyAccessEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }


    public KansasFields withRegistrationType(KansasRegistrationType registrationType) {
        Utils.checkNotNull(registrationType, "registrationType");
        this.registrationType = registrationType;
        return this;
    }

    /**
     * State-registered business name as shown in the Kansas tax portal.
     */
    public KansasFields withBusinessName(String businessName) {
        Utils.checkNotNull(businessName, "businessName");
        this.businessName = businessName;
        return this;
    }

    /**
     * Kansas state-issued tax identification number.
     */
    public KansasFields withKsStateTaxId(String ksStateTaxId) {
        Utils.checkNotNull(ksStateTaxId, "ksStateTaxId");
        this.ksStateTaxId = ksStateTaxId;
        return this;
    }

    /**
     * Kansas Access Code used for portal access / third-party setup.
     */
    public KansasFields withAccessCode(String accessCode) {
        Utils.checkNotNull(accessCode, "accessCode");
        this.accessCode = accessCode;
        return this;
    }

    /**
     * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
     * informed via footer copy; Kintsugi implements access on their behalf.
     */
    public KansasFields withThirdPartyAccessEnabled(boolean thirdPartyAccessEnabled) {
        Utils.checkNotNull(thirdPartyAccessEnabled, "thirdPartyAccessEnabled");
        this.thirdPartyAccessEnabled = Optional.ofNullable(thirdPartyAccessEnabled);
        return this;
    }


    /**
     * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
     * informed via footer copy; Kintsugi implements access on their behalf.
     */
    public KansasFields withThirdPartyAccessEnabled(Optional<Boolean> thirdPartyAccessEnabled) {
        Utils.checkNotNull(thirdPartyAccessEnabled, "thirdPartyAccessEnabled");
        this.thirdPartyAccessEnabled = thirdPartyAccessEnabled;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        KansasFields other = (KansasFields) o;
        return 
            Utils.enhancedDeepEquals(this.registrationType, other.registrationType) &&
            Utils.enhancedDeepEquals(this.businessName, other.businessName) &&
            Utils.enhancedDeepEquals(this.ksStateTaxId, other.ksStateTaxId) &&
            Utils.enhancedDeepEquals(this.accessCode, other.accessCode) &&
            Utils.enhancedDeepEquals(this.thirdPartyAccessEnabled, other.thirdPartyAccessEnabled);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            registrationType, businessName, ksStateTaxId,
            accessCode, thirdPartyAccessEnabled);
    }
    
    @Override
    public String toString() {
        return Utils.toString(KansasFields.class,
                "registrationType", registrationType,
                "businessName", businessName,
                "ksStateTaxId", ksStateTaxId,
                "accessCode", accessCode,
                "thirdPartyAccessEnabled", thirdPartyAccessEnabled);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private KansasRegistrationType registrationType;

        private String businessName;

        private String ksStateTaxId;

        private String accessCode;

        private Optional<Boolean> thirdPartyAccessEnabled;

        private Builder() {
          // force use of static builder() method
        }


        public Builder registrationType(KansasRegistrationType registrationType) {
            Utils.checkNotNull(registrationType, "registrationType");
            this.registrationType = registrationType;
            return this;
        }


        /**
         * State-registered business name as shown in the Kansas tax portal.
         */
        public Builder businessName(String businessName) {
            Utils.checkNotNull(businessName, "businessName");
            this.businessName = businessName;
            return this;
        }


        /**
         * Kansas state-issued tax identification number.
         */
        public Builder ksStateTaxId(String ksStateTaxId) {
            Utils.checkNotNull(ksStateTaxId, "ksStateTaxId");
            this.ksStateTaxId = ksStateTaxId;
            return this;
        }


        /**
         * Kansas Access Code used for portal access / third-party setup.
         */
        public Builder accessCode(String accessCode) {
            Utils.checkNotNull(accessCode, "accessCode");
            this.accessCode = accessCode;
            return this;
        }


        /**
         * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
         * informed via footer copy; Kintsugi implements access on their behalf.
         */
        public Builder thirdPartyAccessEnabled(boolean thirdPartyAccessEnabled) {
            Utils.checkNotNull(thirdPartyAccessEnabled, "thirdPartyAccessEnabled");
            this.thirdPartyAccessEnabled = Optional.ofNullable(thirdPartyAccessEnabled);
            return this;
        }

        /**
         * Whether third-party access has been granted to Kintsugi in the Kansas tax portal. Customers are
         * informed via footer copy; Kintsugi implements access on their behalf.
         */
        public Builder thirdPartyAccessEnabled(Optional<Boolean> thirdPartyAccessEnabled) {
            Utils.checkNotNull(thirdPartyAccessEnabled, "thirdPartyAccessEnabled");
            this.thirdPartyAccessEnabled = thirdPartyAccessEnabled;
            return this;
        }

        public KansasFields build() {
            if (thirdPartyAccessEnabled == null) {
                thirdPartyAccessEnabled = _SINGLETON_VALUE_ThirdPartyAccessEnabled.value();
            }

            return new KansasFields(
                registrationType, businessName, ksStateTaxId,
                accessCode, thirdPartyAccessEnabled);
        }


        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_ThirdPartyAccessEnabled =
                new LazySingletonValue<>(
                        "third_party_access_enabled",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});
    }
}
