/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.kintsugi.taxplatform.utils.LazySingletonValue;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * PennsylvaniaFields
 * 
 * <p>State-specific fields for Pennsylvania myPATH registration import.
 */
public class PennsylvaniaFields {
    /**
     * Registration type for this Pennsylvania import: sales and use tax.
     */
    @JsonProperty("registration_type")
    private String registrationType;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Pennsylvania tax account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mfa_completed")
    private Optional<Boolean> mfaCompleted;

    /**
     * State-registered business name as shown in myPATH.
     */
    @JsonProperty("business_name")
    private String businessName;

    /**
     * Pennsylvania state-issued tax identification number (PA License ID).
     */
    @JsonProperty("pa_state_tax_id")
    private String paStateTaxId;

    /**
     * Account ID types accepted when requesting third-party access on Pennsylvania myPATH.
     * 
     * <p>myPATH identifies the account by one of these: a Business Use ID, an Account ID,
     * or a Sales License ID.
     */
    @JsonProperty("account_type")
    private PennsylvaniaAccountType accountType;

    /**
     * Account identifier value matching the selected account ID type.
     */
    @JsonProperty("account_id")
    private String accountId;

    /**
     * Identification types accepted by Pennsylvania myPATH third-party access requests.
     * 
     * <p>myPATH validates the requester against a federal/state identifier: an FEIN, ITIN,
     * Revenue ID, or SSN.
     */
    @JsonProperty("identification_type")
    private PennsylvaniaIdentificationType identificationType;

    /**
     * Identification number value matching the selected identification type.
     */
    @JsonProperty("identification_number")
    private String identificationNumber;

    /**
     * Account validation methods offered by Pennsylvania myPATH third-party access.
     * 
     * <p>The requester proves ownership with exactly one of these: a Letter ID, a Business
     * Registration Confirmation Code, a Payment Amount, or a Return Line Item.
     */
    @JsonProperty("account_validation_method")
    private PennsylvaniaAccountValidationMethod accountValidationMethod;

    /**
     * Value matching the selected account validation method.
     */
    @JsonProperty("account_validation_value")
    private String accountValidationValue;

    /**
     * 11-digit Sales and Use Tax account ID, found in the myPATH account under the Sales and Use Tax card.
     */
    @JsonProperty("sales_and_use_account_id")
    private String salesAndUseAccountId;

    @JsonCreator
    public PennsylvaniaFields(
            @JsonProperty("mfa_completed") Optional<Boolean> mfaCompleted,
            @JsonProperty("business_name") String businessName,
            @JsonProperty("pa_state_tax_id") String paStateTaxId,
            @JsonProperty("account_type") PennsylvaniaAccountType accountType,
            @JsonProperty("account_id") String accountId,
            @JsonProperty("identification_type") PennsylvaniaIdentificationType identificationType,
            @JsonProperty("identification_number") String identificationNumber,
            @JsonProperty("account_validation_method") PennsylvaniaAccountValidationMethod accountValidationMethod,
            @JsonProperty("account_validation_value") String accountValidationValue,
            @JsonProperty("sales_and_use_account_id") String salesAndUseAccountId) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        Utils.checkNotNull(businessName, "businessName");
        Utils.checkNotNull(paStateTaxId, "paStateTaxId");
        Utils.checkNotNull(accountType, "accountType");
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(identificationType, "identificationType");
        Utils.checkNotNull(identificationNumber, "identificationNumber");
        Utils.checkNotNull(accountValidationMethod, "accountValidationMethod");
        Utils.checkNotNull(accountValidationValue, "accountValidationValue");
        Utils.checkNotNull(salesAndUseAccountId, "salesAndUseAccountId");
        this.registrationType = Builder._SINGLETON_VALUE_RegistrationType.value();
        this.mfaCompleted = mfaCompleted;
        this.businessName = businessName;
        this.paStateTaxId = paStateTaxId;
        this.accountType = accountType;
        this.accountId = accountId;
        this.identificationType = identificationType;
        this.identificationNumber = identificationNumber;
        this.accountValidationMethod = accountValidationMethod;
        this.accountValidationValue = accountValidationValue;
        this.salesAndUseAccountId = salesAndUseAccountId;
    }
    
    public PennsylvaniaFields(
            String businessName,
            String paStateTaxId,
            PennsylvaniaAccountType accountType,
            String accountId,
            PennsylvaniaIdentificationType identificationType,
            String identificationNumber,
            PennsylvaniaAccountValidationMethod accountValidationMethod,
            String accountValidationValue,
            String salesAndUseAccountId) {
        this(Optional.empty(), businessName, paStateTaxId,
            accountType, accountId, identificationType,
            identificationNumber, accountValidationMethod, accountValidationValue,
            salesAndUseAccountId);
    }

    /**
     * Registration type for this Pennsylvania import: sales and use tax.
     */
    @JsonIgnore
    public String registrationType() {
        return registrationType;
    }

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Pennsylvania tax account.
     */
    @JsonIgnore
    public Optional<Boolean> mfaCompleted() {
        return mfaCompleted;
    }

    /**
     * State-registered business name as shown in myPATH.
     */
    @JsonIgnore
    public String businessName() {
        return businessName;
    }

    /**
     * Pennsylvania state-issued tax identification number (PA License ID).
     */
    @JsonIgnore
    public String paStateTaxId() {
        return paStateTaxId;
    }

    /**
     * Account ID types accepted when requesting third-party access on Pennsylvania myPATH.
     * 
     * <p>myPATH identifies the account by one of these: a Business Use ID, an Account ID,
     * or a Sales License ID.
     */
    @JsonIgnore
    public PennsylvaniaAccountType accountType() {
        return accountType;
    }

    /**
     * Account identifier value matching the selected account ID type.
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    /**
     * Identification types accepted by Pennsylvania myPATH third-party access requests.
     * 
     * <p>myPATH validates the requester against a federal/state identifier: an FEIN, ITIN,
     * Revenue ID, or SSN.
     */
    @JsonIgnore
    public PennsylvaniaIdentificationType identificationType() {
        return identificationType;
    }

    /**
     * Identification number value matching the selected identification type.
     */
    @JsonIgnore
    public String identificationNumber() {
        return identificationNumber;
    }

    /**
     * Account validation methods offered by Pennsylvania myPATH third-party access.
     * 
     * <p>The requester proves ownership with exactly one of these: a Letter ID, a Business
     * Registration Confirmation Code, a Payment Amount, or a Return Line Item.
     */
    @JsonIgnore
    public PennsylvaniaAccountValidationMethod accountValidationMethod() {
        return accountValidationMethod;
    }

    /**
     * Value matching the selected account validation method.
     */
    @JsonIgnore
    public String accountValidationValue() {
        return accountValidationValue;
    }

    /**
     * 11-digit Sales and Use Tax account ID, found in the myPATH account under the Sales and Use Tax card.
     */
    @JsonIgnore
    public String salesAndUseAccountId() {
        return salesAndUseAccountId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Pennsylvania tax account.
     */
    public PennsylvaniaFields withMfaCompleted(boolean mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = Optional.ofNullable(mfaCompleted);
        return this;
    }


    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Pennsylvania tax account.
     */
    public PennsylvaniaFields withMfaCompleted(Optional<Boolean> mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = mfaCompleted;
        return this;
    }

    /**
     * State-registered business name as shown in myPATH.
     */
    public PennsylvaniaFields withBusinessName(String businessName) {
        Utils.checkNotNull(businessName, "businessName");
        this.businessName = businessName;
        return this;
    }

    /**
     * Pennsylvania state-issued tax identification number (PA License ID).
     */
    public PennsylvaniaFields withPaStateTaxId(String paStateTaxId) {
        Utils.checkNotNull(paStateTaxId, "paStateTaxId");
        this.paStateTaxId = paStateTaxId;
        return this;
    }

    /**
     * Account ID types accepted when requesting third-party access on Pennsylvania myPATH.
     * 
     * <p>myPATH identifies the account by one of these: a Business Use ID, an Account ID,
     * or a Sales License ID.
     */
    public PennsylvaniaFields withAccountType(PennsylvaniaAccountType accountType) {
        Utils.checkNotNull(accountType, "accountType");
        this.accountType = accountType;
        return this;
    }

    /**
     * Account identifier value matching the selected account ID type.
     */
    public PennsylvaniaFields withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    /**
     * Identification types accepted by Pennsylvania myPATH third-party access requests.
     * 
     * <p>myPATH validates the requester against a federal/state identifier: an FEIN, ITIN,
     * Revenue ID, or SSN.
     */
    public PennsylvaniaFields withIdentificationType(PennsylvaniaIdentificationType identificationType) {
        Utils.checkNotNull(identificationType, "identificationType");
        this.identificationType = identificationType;
        return this;
    }

    /**
     * Identification number value matching the selected identification type.
     */
    public PennsylvaniaFields withIdentificationNumber(String identificationNumber) {
        Utils.checkNotNull(identificationNumber, "identificationNumber");
        this.identificationNumber = identificationNumber;
        return this;
    }

    /**
     * Account validation methods offered by Pennsylvania myPATH third-party access.
     * 
     * <p>The requester proves ownership with exactly one of these: a Letter ID, a Business
     * Registration Confirmation Code, a Payment Amount, or a Return Line Item.
     */
    public PennsylvaniaFields withAccountValidationMethod(PennsylvaniaAccountValidationMethod accountValidationMethod) {
        Utils.checkNotNull(accountValidationMethod, "accountValidationMethod");
        this.accountValidationMethod = accountValidationMethod;
        return this;
    }

    /**
     * Value matching the selected account validation method.
     */
    public PennsylvaniaFields withAccountValidationValue(String accountValidationValue) {
        Utils.checkNotNull(accountValidationValue, "accountValidationValue");
        this.accountValidationValue = accountValidationValue;
        return this;
    }

    /**
     * 11-digit Sales and Use Tax account ID, found in the myPATH account under the Sales and Use Tax card.
     */
    public PennsylvaniaFields withSalesAndUseAccountId(String salesAndUseAccountId) {
        Utils.checkNotNull(salesAndUseAccountId, "salesAndUseAccountId");
        this.salesAndUseAccountId = salesAndUseAccountId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PennsylvaniaFields other = (PennsylvaniaFields) o;
        return 
            Utils.enhancedDeepEquals(this.registrationType, other.registrationType) &&
            Utils.enhancedDeepEquals(this.mfaCompleted, other.mfaCompleted) &&
            Utils.enhancedDeepEquals(this.businessName, other.businessName) &&
            Utils.enhancedDeepEquals(this.paStateTaxId, other.paStateTaxId) &&
            Utils.enhancedDeepEquals(this.accountType, other.accountType) &&
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.identificationType, other.identificationType) &&
            Utils.enhancedDeepEquals(this.identificationNumber, other.identificationNumber) &&
            Utils.enhancedDeepEquals(this.accountValidationMethod, other.accountValidationMethod) &&
            Utils.enhancedDeepEquals(this.accountValidationValue, other.accountValidationValue) &&
            Utils.enhancedDeepEquals(this.salesAndUseAccountId, other.salesAndUseAccountId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            registrationType, mfaCompleted, businessName,
            paStateTaxId, accountType, accountId,
            identificationType, identificationNumber, accountValidationMethod,
            accountValidationValue, salesAndUseAccountId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PennsylvaniaFields.class,
                "registrationType", registrationType,
                "mfaCompleted", mfaCompleted,
                "businessName", businessName,
                "paStateTaxId", paStateTaxId,
                "accountType", accountType,
                "accountId", accountId,
                "identificationType", identificationType,
                "identificationNumber", identificationNumber,
                "accountValidationMethod", accountValidationMethod,
                "accountValidationValue", accountValidationValue,
                "salesAndUseAccountId", salesAndUseAccountId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Boolean> mfaCompleted;

        private String businessName;

        private String paStateTaxId;

        private PennsylvaniaAccountType accountType;

        private String accountId;

        private PennsylvaniaIdentificationType identificationType;

        private String identificationNumber;

        private PennsylvaniaAccountValidationMethod accountValidationMethod;

        private String accountValidationValue;

        private String salesAndUseAccountId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
         * Pennsylvania tax account.
         */
        public Builder mfaCompleted(boolean mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = Optional.ofNullable(mfaCompleted);
            return this;
        }

        /**
         * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
         * Pennsylvania tax account.
         */
        public Builder mfaCompleted(Optional<Boolean> mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = mfaCompleted;
            return this;
        }


        /**
         * State-registered business name as shown in myPATH.
         */
        public Builder businessName(String businessName) {
            Utils.checkNotNull(businessName, "businessName");
            this.businessName = businessName;
            return this;
        }


        /**
         * Pennsylvania state-issued tax identification number (PA License ID).
         */
        public Builder paStateTaxId(String paStateTaxId) {
            Utils.checkNotNull(paStateTaxId, "paStateTaxId");
            this.paStateTaxId = paStateTaxId;
            return this;
        }


        /**
         * Account ID types accepted when requesting third-party access on Pennsylvania myPATH.
         * 
         * <p>myPATH identifies the account by one of these: a Business Use ID, an Account ID,
         * or a Sales License ID.
         */
        public Builder accountType(PennsylvaniaAccountType accountType) {
            Utils.checkNotNull(accountType, "accountType");
            this.accountType = accountType;
            return this;
        }


        /**
         * Account identifier value matching the selected account ID type.
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        /**
         * Identification types accepted by Pennsylvania myPATH third-party access requests.
         * 
         * <p>myPATH validates the requester against a federal/state identifier: an FEIN, ITIN,
         * Revenue ID, or SSN.
         */
        public Builder identificationType(PennsylvaniaIdentificationType identificationType) {
            Utils.checkNotNull(identificationType, "identificationType");
            this.identificationType = identificationType;
            return this;
        }


        /**
         * Identification number value matching the selected identification type.
         */
        public Builder identificationNumber(String identificationNumber) {
            Utils.checkNotNull(identificationNumber, "identificationNumber");
            this.identificationNumber = identificationNumber;
            return this;
        }


        /**
         * Account validation methods offered by Pennsylvania myPATH third-party access.
         * 
         * <p>The requester proves ownership with exactly one of these: a Letter ID, a Business
         * Registration Confirmation Code, a Payment Amount, or a Return Line Item.
         */
        public Builder accountValidationMethod(PennsylvaniaAccountValidationMethod accountValidationMethod) {
            Utils.checkNotNull(accountValidationMethod, "accountValidationMethod");
            this.accountValidationMethod = accountValidationMethod;
            return this;
        }


        /**
         * Value matching the selected account validation method.
         */
        public Builder accountValidationValue(String accountValidationValue) {
            Utils.checkNotNull(accountValidationValue, "accountValidationValue");
            this.accountValidationValue = accountValidationValue;
            return this;
        }


        /**
         * 11-digit Sales and Use Tax account ID, found in the myPATH account under the Sales and Use Tax card.
         */
        public Builder salesAndUseAccountId(String salesAndUseAccountId) {
            Utils.checkNotNull(salesAndUseAccountId, "salesAndUseAccountId");
            this.salesAndUseAccountId = salesAndUseAccountId;
            return this;
        }

        public PennsylvaniaFields build() {
            if (mfaCompleted == null) {
                mfaCompleted = _SINGLETON_VALUE_MfaCompleted.value();
            }

            return new PennsylvaniaFields(
                mfaCompleted, businessName, paStateTaxId,
                accountType, accountId, identificationType,
                identificationNumber, accountValidationMethod, accountValidationValue,
                salesAndUseAccountId);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_RegistrationType =
                new LazySingletonValue<>(
                        "registration_type",
                        "\"SALES_AND_USE_TAX\"",
                        new TypeReference<String>() {});

        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_MfaCompleted =
                new LazySingletonValue<>(
                        "mfa_completed",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});
    }
}
