/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;


public class PhysicalNexusUpdate {
    /**
     * The date when the nexus became
     * effective (YYYY-MM-DD).
     */
    @JsonProperty("start_date")
    private LocalDate startDate;

    /**
     * The date when the
     * nexus ends, if applicable (YYYY-MM-DD).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end_date")
    private JsonNullable<LocalDate> endDate;


    @JsonProperty("category")
    private PhysicalNexusCategory category;

    /**
     * Primary street address for the physical presence location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street_1")
    private JsonNullable<String> street1;

    /**
     * Additional street address details, such as suite or unit number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street_2")
    private JsonNullable<String> street2;

    /**
     * City of the physical presence location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    private JsonNullable<String> city;

    /**
     * ZIP or postal code of the physical presence location.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postal_code")
    private JsonNullable<String> postalCode;

    @JsonCreator
    public PhysicalNexusUpdate(
            @JsonProperty("start_date") LocalDate startDate,
            @JsonProperty("end_date") JsonNullable<LocalDate> endDate,
            @JsonProperty("category") PhysicalNexusCategory category,
            @JsonProperty("street_1") JsonNullable<String> street1,
            @JsonProperty("street_2") JsonNullable<String> street2,
            @JsonProperty("city") JsonNullable<String> city,
            @JsonProperty("postal_code") JsonNullable<String> postalCode) {
        Utils.checkNotNull(startDate, "startDate");
        Utils.checkNotNull(endDate, "endDate");
        Utils.checkNotNull(category, "category");
        Utils.checkNotNull(street1, "street1");
        Utils.checkNotNull(street2, "street2");
        Utils.checkNotNull(city, "city");
        Utils.checkNotNull(postalCode, "postalCode");
        this.startDate = startDate;
        this.endDate = endDate;
        this.category = category;
        this.street1 = street1;
        this.street2 = street2;
        this.city = city;
        this.postalCode = postalCode;
    }
    
    public PhysicalNexusUpdate(
            LocalDate startDate,
            PhysicalNexusCategory category) {
        this(startDate, JsonNullable.undefined(), category,
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined());
    }

    /**
     * The date when the nexus became
     * effective (YYYY-MM-DD).
     */
    @JsonIgnore
    public LocalDate startDate() {
        return startDate;
    }

    /**
     * The date when the
     * nexus ends, if applicable (YYYY-MM-DD).
     */
    @JsonIgnore
    public JsonNullable<LocalDate> endDate() {
        return endDate;
    }

    @JsonIgnore
    public PhysicalNexusCategory category() {
        return category;
    }

    /**
     * Primary street address for the physical presence location.
     */
    @JsonIgnore
    public JsonNullable<String> street1() {
        return street1;
    }

    /**
     * Additional street address details, such as suite or unit number.
     */
    @JsonIgnore
    public JsonNullable<String> street2() {
        return street2;
    }

    /**
     * City of the physical presence location.
     */
    @JsonIgnore
    public JsonNullable<String> city() {
        return city;
    }

    /**
     * ZIP or postal code of the physical presence location.
     */
    @JsonIgnore
    public JsonNullable<String> postalCode() {
        return postalCode;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The date when the nexus became
     * effective (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withStartDate(LocalDate startDate) {
        Utils.checkNotNull(startDate, "startDate");
        this.startDate = startDate;
        return this;
    }

    /**
     * The date when the
     * nexus ends, if applicable (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withEndDate(LocalDate endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = JsonNullable.of(endDate);
        return this;
    }

    /**
     * The date when the
     * nexus ends, if applicable (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withEndDate(JsonNullable<LocalDate> endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = endDate;
        return this;
    }

    public PhysicalNexusUpdate withCategory(PhysicalNexusCategory category) {
        Utils.checkNotNull(category, "category");
        this.category = category;
        return this;
    }

    /**
     * Primary street address for the physical presence location.
     */
    public PhysicalNexusUpdate withStreet1(String street1) {
        Utils.checkNotNull(street1, "street1");
        this.street1 = JsonNullable.of(street1);
        return this;
    }

    /**
     * Primary street address for the physical presence location.
     */
    public PhysicalNexusUpdate withStreet1(JsonNullable<String> street1) {
        Utils.checkNotNull(street1, "street1");
        this.street1 = street1;
        return this;
    }

    /**
     * Additional street address details, such as suite or unit number.
     */
    public PhysicalNexusUpdate withStreet2(String street2) {
        Utils.checkNotNull(street2, "street2");
        this.street2 = JsonNullable.of(street2);
        return this;
    }

    /**
     * Additional street address details, such as suite or unit number.
     */
    public PhysicalNexusUpdate withStreet2(JsonNullable<String> street2) {
        Utils.checkNotNull(street2, "street2");
        this.street2 = street2;
        return this;
    }

    /**
     * City of the physical presence location.
     */
    public PhysicalNexusUpdate withCity(String city) {
        Utils.checkNotNull(city, "city");
        this.city = JsonNullable.of(city);
        return this;
    }

    /**
     * City of the physical presence location.
     */
    public PhysicalNexusUpdate withCity(JsonNullable<String> city) {
        Utils.checkNotNull(city, "city");
        this.city = city;
        return this;
    }

    /**
     * ZIP or postal code of the physical presence location.
     */
    public PhysicalNexusUpdate withPostalCode(String postalCode) {
        Utils.checkNotNull(postalCode, "postalCode");
        this.postalCode = JsonNullable.of(postalCode);
        return this;
    }

    /**
     * ZIP or postal code of the physical presence location.
     */
    public PhysicalNexusUpdate withPostalCode(JsonNullable<String> postalCode) {
        Utils.checkNotNull(postalCode, "postalCode");
        this.postalCode = postalCode;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PhysicalNexusUpdate other = (PhysicalNexusUpdate) o;
        return 
            Utils.enhancedDeepEquals(this.startDate, other.startDate) &&
            Utils.enhancedDeepEquals(this.endDate, other.endDate) &&
            Utils.enhancedDeepEquals(this.category, other.category) &&
            Utils.enhancedDeepEquals(this.street1, other.street1) &&
            Utils.enhancedDeepEquals(this.street2, other.street2) &&
            Utils.enhancedDeepEquals(this.city, other.city) &&
            Utils.enhancedDeepEquals(this.postalCode, other.postalCode);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            startDate, endDate, category,
            street1, street2, city,
            postalCode);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PhysicalNexusUpdate.class,
                "startDate", startDate,
                "endDate", endDate,
                "category", category,
                "street1", street1,
                "street2", street2,
                "city", city,
                "postalCode", postalCode);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private LocalDate startDate;

        private JsonNullable<LocalDate> endDate = JsonNullable.undefined();

        private PhysicalNexusCategory category;

        private JsonNullable<String> street1 = JsonNullable.undefined();

        private JsonNullable<String> street2 = JsonNullable.undefined();

        private JsonNullable<String> city = JsonNullable.undefined();

        private JsonNullable<String> postalCode = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The date when the nexus became
         * effective (YYYY-MM-DD).
         */
        public Builder startDate(LocalDate startDate) {
            Utils.checkNotNull(startDate, "startDate");
            this.startDate = startDate;
            return this;
        }


        /**
         * The date when the
         * nexus ends, if applicable (YYYY-MM-DD).
         */
        public Builder endDate(LocalDate endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = JsonNullable.of(endDate);
            return this;
        }

        /**
         * The date when the
         * nexus ends, if applicable (YYYY-MM-DD).
         */
        public Builder endDate(JsonNullable<LocalDate> endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = endDate;
            return this;
        }


        public Builder category(PhysicalNexusCategory category) {
            Utils.checkNotNull(category, "category");
            this.category = category;
            return this;
        }


        /**
         * Primary street address for the physical presence location.
         */
        public Builder street1(String street1) {
            Utils.checkNotNull(street1, "street1");
            this.street1 = JsonNullable.of(street1);
            return this;
        }

        /**
         * Primary street address for the physical presence location.
         */
        public Builder street1(JsonNullable<String> street1) {
            Utils.checkNotNull(street1, "street1");
            this.street1 = street1;
            return this;
        }


        /**
         * Additional street address details, such as suite or unit number.
         */
        public Builder street2(String street2) {
            Utils.checkNotNull(street2, "street2");
            this.street2 = JsonNullable.of(street2);
            return this;
        }

        /**
         * Additional street address details, such as suite or unit number.
         */
        public Builder street2(JsonNullable<String> street2) {
            Utils.checkNotNull(street2, "street2");
            this.street2 = street2;
            return this;
        }


        /**
         * City of the physical presence location.
         */
        public Builder city(String city) {
            Utils.checkNotNull(city, "city");
            this.city = JsonNullable.of(city);
            return this;
        }

        /**
         * City of the physical presence location.
         */
        public Builder city(JsonNullable<String> city) {
            Utils.checkNotNull(city, "city");
            this.city = city;
            return this;
        }


        /**
         * ZIP or postal code of the physical presence location.
         */
        public Builder postalCode(String postalCode) {
            Utils.checkNotNull(postalCode, "postalCode");
            this.postalCode = JsonNullable.of(postalCode);
            return this;
        }

        /**
         * ZIP or postal code of the physical presence location.
         */
        public Builder postalCode(JsonNullable<String> postalCode) {
            Utils.checkNotNull(postalCode, "postalCode");
            this.postalCode = postalCode;
            return this;
        }

        public PhysicalNexusUpdate build() {

            return new PhysicalNexusUpdate(
                startDate, endDate, category,
                street1, street2, city,
                postalCode);
        }

    }
}
