/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import java.util.Optional;


public class PhysicalNexusUpdate {
    /**
     * The date when the nexus became
     *                                 effective (YYYY-MM-DD).
     */
    @JsonProperty("start_date")
    private LocalDate startDate;

    /**
     * The date when the
     *                                         nexus ends, if applicable (YYYY-MM-DD).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end_date")
    private Optional<String> endDate;


    @JsonProperty("category")
    private PhysicalNexusCategory category;

    @JsonCreator
    public PhysicalNexusUpdate(
            @JsonProperty("start_date") LocalDate startDate,
            @JsonProperty("end_date") Optional<String> endDate,
            @JsonProperty("category") PhysicalNexusCategory category) {
        Utils.checkNotNull(startDate, "startDate");
        Utils.checkNotNull(endDate, "endDate");
        Utils.checkNotNull(category, "category");
        this.startDate = startDate;
        this.endDate = endDate;
        this.category = category;
    }
    
    public PhysicalNexusUpdate(
            LocalDate startDate,
            PhysicalNexusCategory category) {
        this(startDate, Optional.empty(), category);
    }

    /**
     * The date when the nexus became
     *                                 effective (YYYY-MM-DD).
     */
    @JsonIgnore
    public LocalDate startDate() {
        return startDate;
    }

    /**
     * The date when the
     *                                         nexus ends, if applicable (YYYY-MM-DD).
     */
    @JsonIgnore
    public Optional<String> endDate() {
        return endDate;
    }

    @JsonIgnore
    public PhysicalNexusCategory category() {
        return category;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The date when the nexus became
     *                                 effective (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withStartDate(LocalDate startDate) {
        Utils.checkNotNull(startDate, "startDate");
        this.startDate = startDate;
        return this;
    }

    /**
     * The date when the
     *                                         nexus ends, if applicable (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withEndDate(String endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = Optional.ofNullable(endDate);
        return this;
    }


    /**
     * The date when the
     *                                         nexus ends, if applicable (YYYY-MM-DD).
     */
    public PhysicalNexusUpdate withEndDate(Optional<String> endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = endDate;
        return this;
    }

    public PhysicalNexusUpdate withCategory(PhysicalNexusCategory category) {
        Utils.checkNotNull(category, "category");
        this.category = category;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PhysicalNexusUpdate other = (PhysicalNexusUpdate) o;
        return 
            Utils.enhancedDeepEquals(this.startDate, other.startDate) &&
            Utils.enhancedDeepEquals(this.endDate, other.endDate) &&
            Utils.enhancedDeepEquals(this.category, other.category);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            startDate, endDate, category);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PhysicalNexusUpdate.class,
                "startDate", startDate,
                "endDate", endDate,
                "category", category);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private LocalDate startDate;

        private Optional<String> endDate = Optional.empty();

        private PhysicalNexusCategory category;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The date when the nexus became
         *                                 effective (YYYY-MM-DD).
         */
        public Builder startDate(LocalDate startDate) {
            Utils.checkNotNull(startDate, "startDate");
            this.startDate = startDate;
            return this;
        }


        /**
         * The date when the
         *                                         nexus ends, if applicable (YYYY-MM-DD).
         */
        public Builder endDate(String endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        /**
         * The date when the
         *                                         nexus ends, if applicable (YYYY-MM-DD).
         */
        public Builder endDate(Optional<String> endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = endDate;
            return this;
        }


        public Builder category(PhysicalNexusCategory category) {
            Utils.checkNotNull(category, "category");
            this.category = category;
            return this;
        }

        public PhysicalNexusUpdate build() {

            return new PhysicalNexusUpdate(
                startDate, endDate, category);
        }

    }
}
