/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.kintsugi.taxplatform.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.kintsugi.taxplatform.utils.LazySingletonValue;
import com.kintsugi.taxplatform.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * TennesseeFields
 * 
 * <p>State-specific fields for Tennessee TNTAP portal registration import.
 */
public class TennesseeFields {

    @JsonProperty("registration_type")
    private TennesseeRegistrationType registrationType;

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Tennessee DOR TNTAP account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mfa_completed")
    private Optional<Boolean> mfaCompleted;

    /**
     * State-registered business name as shown in TNTAP.
     */
    @JsonProperty("business_name")
    private String businessName;

    /**
     * Tennessee state-issued tax identification number (TN State Tax ID).
     */
    @JsonProperty("tn_state_tax_id")
    private String tnStateTaxId;

    /**
     * Account ZIP code on file with the Tennessee Department of Revenue.
     */
    @JsonProperty("zip_code")
    private String zipCode;

    /**
     * Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed
     * by 10 digits (e.g. L1234567890).
     */
    @JsonProperty("letter_id")
    private String letterId;

    @JsonCreator
    public TennesseeFields(
            @JsonProperty("registration_type") TennesseeRegistrationType registrationType,
            @JsonProperty("mfa_completed") Optional<Boolean> mfaCompleted,
            @JsonProperty("business_name") String businessName,
            @JsonProperty("tn_state_tax_id") String tnStateTaxId,
            @JsonProperty("zip_code") String zipCode,
            @JsonProperty("letter_id") String letterId) {
        Utils.checkNotNull(registrationType, "registrationType");
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        Utils.checkNotNull(businessName, "businessName");
        Utils.checkNotNull(tnStateTaxId, "tnStateTaxId");
        Utils.checkNotNull(zipCode, "zipCode");
        Utils.checkNotNull(letterId, "letterId");
        this.registrationType = registrationType;
        this.mfaCompleted = mfaCompleted;
        this.businessName = businessName;
        this.tnStateTaxId = tnStateTaxId;
        this.zipCode = zipCode;
        this.letterId = letterId;
    }
    
    public TennesseeFields(
            TennesseeRegistrationType registrationType,
            String businessName,
            String tnStateTaxId,
            String zipCode,
            String letterId) {
        this(registrationType, Optional.empty(), businessName,
            tnStateTaxId, zipCode, letterId);
    }

    @JsonIgnore
    public TennesseeRegistrationType registrationType() {
        return registrationType;
    }

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Tennessee DOR TNTAP account.
     */
    @JsonIgnore
    public Optional<Boolean> mfaCompleted() {
        return mfaCompleted;
    }

    /**
     * State-registered business name as shown in TNTAP.
     */
    @JsonIgnore
    public String businessName() {
        return businessName;
    }

    /**
     * Tennessee state-issued tax identification number (TN State Tax ID).
     */
    @JsonIgnore
    public String tnStateTaxId() {
        return tnStateTaxId;
    }

    /**
     * Account ZIP code on file with the Tennessee Department of Revenue.
     */
    @JsonIgnore
    public String zipCode() {
        return zipCode;
    }

    /**
     * Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed
     * by 10 digits (e.g. L1234567890).
     */
    @JsonIgnore
    public String letterId() {
        return letterId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public TennesseeFields withRegistrationType(TennesseeRegistrationType registrationType) {
        Utils.checkNotNull(registrationType, "registrationType");
        this.registrationType = registrationType;
        return this;
    }

    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Tennessee DOR TNTAP account.
     */
    public TennesseeFields withMfaCompleted(boolean mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = Optional.ofNullable(mfaCompleted);
        return this;
    }


    /**
     * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
     * Tennessee DOR TNTAP account.
     */
    public TennesseeFields withMfaCompleted(Optional<Boolean> mfaCompleted) {
        Utils.checkNotNull(mfaCompleted, "mfaCompleted");
        this.mfaCompleted = mfaCompleted;
        return this;
    }

    /**
     * State-registered business name as shown in TNTAP.
     */
    public TennesseeFields withBusinessName(String businessName) {
        Utils.checkNotNull(businessName, "businessName");
        this.businessName = businessName;
        return this;
    }

    /**
     * Tennessee state-issued tax identification number (TN State Tax ID).
     */
    public TennesseeFields withTnStateTaxId(String tnStateTaxId) {
        Utils.checkNotNull(tnStateTaxId, "tnStateTaxId");
        this.tnStateTaxId = tnStateTaxId;
        return this;
    }

    /**
     * Account ZIP code on file with the Tennessee Department of Revenue.
     */
    public TennesseeFields withZipCode(String zipCode) {
        Utils.checkNotNull(zipCode, "zipCode");
        this.zipCode = zipCode;
        return this;
    }

    /**
     * Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed
     * by 10 digits (e.g. L1234567890).
     */
    public TennesseeFields withLetterId(String letterId) {
        Utils.checkNotNull(letterId, "letterId");
        this.letterId = letterId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TennesseeFields other = (TennesseeFields) o;
        return 
            Utils.enhancedDeepEquals(this.registrationType, other.registrationType) &&
            Utils.enhancedDeepEquals(this.mfaCompleted, other.mfaCompleted) &&
            Utils.enhancedDeepEquals(this.businessName, other.businessName) &&
            Utils.enhancedDeepEquals(this.tnStateTaxId, other.tnStateTaxId) &&
            Utils.enhancedDeepEquals(this.zipCode, other.zipCode) &&
            Utils.enhancedDeepEquals(this.letterId, other.letterId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            registrationType, mfaCompleted, businessName,
            tnStateTaxId, zipCode, letterId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TennesseeFields.class,
                "registrationType", registrationType,
                "mfaCompleted", mfaCompleted,
                "businessName", businessName,
                "tnStateTaxId", tnStateTaxId,
                "zipCode", zipCode,
                "letterId", letterId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private TennesseeRegistrationType registrationType;

        private Optional<Boolean> mfaCompleted;

        private String businessName;

        private String tnStateTaxId;

        private String zipCode;

        private String letterId;

        private Builder() {
          // force use of static builder() method
        }


        public Builder registrationType(TennesseeRegistrationType registrationType) {
            Utils.checkNotNull(registrationType, "registrationType");
            this.registrationType = registrationType;
            return this;
        }


        /**
         * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
         * Tennessee DOR TNTAP account.
         */
        public Builder mfaCompleted(boolean mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = Optional.ofNullable(mfaCompleted);
            return this;
        }

        /**
         * Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their
         * Tennessee DOR TNTAP account.
         */
        public Builder mfaCompleted(Optional<Boolean> mfaCompleted) {
            Utils.checkNotNull(mfaCompleted, "mfaCompleted");
            this.mfaCompleted = mfaCompleted;
            return this;
        }


        /**
         * State-registered business name as shown in TNTAP.
         */
        public Builder businessName(String businessName) {
            Utils.checkNotNull(businessName, "businessName");
            this.businessName = businessName;
            return this;
        }


        /**
         * Tennessee state-issued tax identification number (TN State Tax ID).
         */
        public Builder tnStateTaxId(String tnStateTaxId) {
            Utils.checkNotNull(tnStateTaxId, "tnStateTaxId");
            this.tnStateTaxId = tnStateTaxId;
            return this;
        }


        /**
         * Account ZIP code on file with the Tennessee Department of Revenue.
         */
        public Builder zipCode(String zipCode) {
            Utils.checkNotNull(zipCode, "zipCode");
            this.zipCode = zipCode;
            return this;
        }


        /**
         * Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed
         * by 10 digits (e.g. L1234567890).
         */
        public Builder letterId(String letterId) {
            Utils.checkNotNull(letterId, "letterId");
            this.letterId = letterId;
            return this;
        }

        public TennesseeFields build() {
            if (mfaCompleted == null) {
                mfaCompleted = _SINGLETON_VALUE_MfaCompleted.value();
            }

            return new TennesseeFields(
                registrationType, mfaCompleted, businessName,
                tnStateTaxId, zipCode, letterId);
        }


        private static final LazySingletonValue<Optional<Boolean>> _SINGLETON_VALUE_MfaCompleted =
                new LazySingletonValue<>(
                        "mfa_completed",
                        "false",
                        new TypeReference<Optional<Boolean>>() {});
    }
}
